apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocation-ecr-rep-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: geolocation-ecr-rep-app
  template:
    metadata:
      labels:
        app: geolocation-ecr-rep-app
    spec:
      containers:
      - name: geolocation-ecr-rep-app
        image: 259289693704.dkr.ecr.us-east-2.amazonaws.com/geolocation_ecr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
